//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SocialWorkerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndirectStudentSrv
    {
        public long ID { get; set; }
        public string SoicialWorker { get; set; }
        public int ReportMonthID { get; set; }
        public string SiteId { get; set; }
        public int TPDevAttend { get; set; }
        public int TPDevFacilitated { get; set; }
        public int CollabWorkParticipated { get; set; }
        public string ContributedToSafeSchool { get; set; }
        public string TechUsed { get; set; }
        public int StudentAdvocacy { get; set; }
        public int FamilyAdvocacy { get; set; }
        public int SchoolStaffConsultation { get; set; }
        public int AttenedTraining { get; set; }
        public int ProfessionalDevelopmentFacilitated { get; set; }
        public int ISSOtherNo { get; set; }
        public string ISSOtherText { get; set; }
        public int ISTmeetings { get; set; }
        public int C504meetings { get; set; }
        public int PBISmeetings { get; set; }
        public int IEPmeetings { get; set; }
        public int CPSteam { get; set; }
        public int CandSOtherNo { get; set; }
        public string CandSOtherText { get; set; }
        public int ParentCourtReferrals { get; set; }
        public int JuvenileCourtReferrals { get; set; }
        public int CPSReferrals { get; set; }
        public int DHHSReferrals { get; set; }
        public int PublicMentalHealthReferrals { get; set; }
        public int MentalHealthAgencyReferrals { get; set; }
        public int SubstanceAbuseServicesReferrals { get; set; }
        public int HomelessnessServicesReferrals { get; set; }
        public int FaithCommunityReferrals { get; set; }
        public int BusinessPartnerReferrals { get; set; }
        public byte Active { get; set; }
    }
}
