//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SocialWorkerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherDuty
    {
        public long ID { get; set; }
        public string SoicialWorker { get; set; }
        public int ReportMonthID { get; set; }
        public string SiteId { get; set; }
        public byte CarRiderDuty { get; set; }
        public byte BusDuty { get; set; }
        public byte LunchDuty { get; set; }
        public byte HallDuty { get; set; }
        public byte AddressVerification { get; set; }
        public byte LongTermSuspension { get; set; }
        public byte Homelessness { get; set; }
        public byte BenchMarks { get; set; }
        public byte ODOtherNo { get; set; }
        public string ODOtherText { get; set; }
        public byte Active { get; set; }
    }
}
