//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SocialWorkerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsive
    {
        public long ID { get; set; }
        public string SoicialWorker { get; set; }
        public int ReportMonthID { get; set; }
        public string SiteId { get; set; }
        public int IndividualCounselingSession { get; set; }
        public int SmallGroupSession { get; set; }
        public int ClassRoomSession { get; set; }
        public int ParentConferences { get; set; }
        public int HomeVisits { get; set; }
        public int ParentTelephoneCalls { get; set; }
        public int ParentWorkshopsFacilitated { get; set; }
        public int SITInterventions { get; set; }
        public int OtherServices { get; set; }
        public byte DrugFactsActionPack { get; set; }
        public byte WiseOwls { get; set; }
        public int SMARTTeam { get; set; }
        public byte BullyProofingSchools { get; set; }
        public byte ConflictResolution { get; set; }
        public byte HabitsofHighlyEffectiveTeens { get; set; }
        public byte SupportGroupActivities { get; set; }
        public byte AllAboutMe { get; set; }
        public byte SkillsforGrowing { get; set; }
        public byte Peacemakers { get; set; }
        public byte TheOtherWesMoore { get; set; }
        public byte HowChildrenSucceed { get; set; }
        public byte SocialWorkToolkit { get; set; }
        public byte DaysandCounting { get; set; }
        public byte WhyTry { get; set; }
        public byte ToolsforTeachingSocialSkills { get; set; }
        public byte CurriculumOther { get; set; }
        public byte Active { get; set; }
    }
}
