//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SocialWorkerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReferral
    {
        public long ID { get; set; }
        public string SoicialWorker { get; set; }
        public int ReportMonthID { get; set; }
        public string SiteId { get; set; }
        public Nullable<int> AmericanIndianFemale { get; set; }
        public int AmericanIndianMale { get; set; }
        public int AsianFemale { get; set; }
        public int AsianMale { get; set; }
        public int BlackFemale { get; set; }
        public int BlackMale { get; set; }
        public int HispanicFemale { get; set; }
        public int HispanicMale { get; set; }
        public int MultiracialFemale { get; set; }
        public int MultiracialMale { get; set; }
        public int WhiteFemale { get; set; }
        public int WhiteMale { get; set; }
        public byte AcademicPerformance { get; set; }
        public byte AbuseNeglectConsult { get; set; }
        public byte AdministrativeRequest { get; set; }
        public byte AlcoholDrugSubstanceAbuse { get; set; }
        public byte Attendance { get; set; }
        public byte BehaviorManagement { get; set; }
        public byte Bullying { get; set; }
        public byte CharacterDevelopment { get; set; }
        public byte ConflictResolution { get; set; }
        public byte DropoutPrevention { get; set; }
        public byte ECReferrals { get; set; }
        public byte EmergencyAssistance { get; set; }
        public byte HealthDental { get; set; }
        public byte Homelessness { get; set; }
        public byte MentalHealth { get; set; }
        public byte NeedsAssessment { get; set; }
        public byte SIT { get; set; }
        public byte SMOD { get; set; }
        public byte SocialServiceNeeds { get; set; }
        public byte SuspensionFollowup { get; set; }
        public byte Active { get; set; }
    }
}
