//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SocialWorkerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialWorkersAppEntities : DbContext
    {
        public SocialWorkersAppEntities()
            : base("name=SocialWorkersAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssmentScreening> AssmentScreenings { get; set; }
        public virtual DbSet<IndirectStudentSrv> IndirectStudentSrvs { get; set; }
        public virtual DbSet<OtherDuty> OtherDuties { get; set; }
        public virtual DbSet<Responsive> Responsives { get; set; }
        public virtual DbSet<StudentReferral> StudentReferrals { get; set; }
        public virtual DbSet<vew_SchoolInfo> vew_SchoolInfo { get; set; }
    }
}
