//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_SocialWorkerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vew_SchoolInfo
    {
        public string SiteId { get; set; }
        public string SiteName { get; set; }
        public string Principal { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string SchoolType { get; set; }
    }
}
