CREATE TABLE [dbo].StudentReferrals(
	ID bigint NOT NULL,
	SoicialWorker varchar(10) NOT NULL,
	ReportMonthID int NOT NULL  DEFAULT 0,
	AmericanIndianFemale int  NULL DEFAULT 0,
	AmericanIndianMale int NOT NULL DEFAULT 0,
	AsianFemale int NOT NULL DEFAULT 0,
	AsianMale int NOT NULL DEFAULT 0,
	BlackFemale int NOT NULL DEFAULT 0,
	BlackMale int NOT NULL DEFAULT 0,
	HispanicFemale int NOT NULL DEFAULT 0,
	HispanicMale int NOT NULL DEFAULT 0,
	MultiracialFemale int NOT NULL DEFAULT 0,
	MultiracialMale int NOT NULL DEFAULT 0,
	WhiteFemale int NOT NULL DEFAULT 0,
	WhiteMale int NOT NULL DEFAULT 0,
	AcademicPerformance tinyint NOT NULL DEFAULT 0,
	AbuseNeglectConsult tinyint NOT NULL DEFAULT 0,
	AdministrativeRequest tinyint NOT NULL DEFAULT 0,
	AlcoholDrugSubstanceAbuse tinyint NOT NULL DEFAULT 0,
	Attendance tinyint NOT NULL DEFAULT 0,
	BehaviorManagement tinyint NOT NULL DEFAULT 0,
	Bullying tinyint NOT NULL DEFAULT 0,
	CharacterDevelopment tinyint NOT NULL DEFAULT 0,
	ConflictResolution tinyint NOT NULL DEFAULT 0,
	DropoutPrevention tinyint NOT NULL DEFAULT 0,
	ECReferrals tinyint NOT NULL DEFAULT 0,
	EmergencyAssistance tinyint NOT NULL DEFAULT 0,
	HealthDental tinyint NOT NULL DEFAULT 0,
	Homelessness tinyint NOT NULL DEFAULT 0,
	MentalHealth tinyint NOT NULL DEFAULT 0,
	NeedsAssessment tinyint NOT NULL DEFAULT 0,
	SIT tinyint NOT NULL DEFAULT 0,
	SMOD tinyint NOT NULL DEFAULT 0,
	SocialServiceNeeds tinyint NOT NULL DEFAULT 0,
	SuspensionFollowup tinyint NOT NULL DEFAULT 0,
	Active tinyint NOT NULL DEFAULT 1
	)
